### ISSUE TITLE
Fedora 38

### ISSUE THREAD

**Issue by giladwo** [VSWSL/Fedora-WSL#21]
Hi, thanks for maintaining this project :)

Are there any plans for upgrading the base image to Fedora 38 (and subsequent releases, considering the short life span of official Fedora releases)?

**Comment by vineelsai26** [comment]
Hey, i have already updated the base image to fedora 38 and published it to Microsoft store over a month ago, you won't be able to update the app from Microsoft store and directly get upgraded to fedora 38, you either have to reset the app from settings or uninstall and reinstall for the base to change, if you don't want to loose any data manually updating to new version is the best choice. I am planning to update the base to all new releases for the foreseeable future.
