### ISSUE TITLE
Getting GUI apps to work: Gitkraken

### ISSUE THREAD

**Issue by atirut-w** [VSWSL/Fedora-WSL#23]
- After installing Gitkraken, there are still missing library that are somehow not marked as dependencies. The GK devs probably expected them to already be there, hence they did not add them as dependencies. I will make a list of what are missing later.
- GK gets stuck on the loading splash screen. I have yet to investigate what happened.

**Comment by vineelsai26** [comment]
This seems to be a specific issue with Gitkraken and I can't install all the packages that are included in the workstation(guessing Gitkraken might assume that so not added them in dependency list) as it will increase the download size significantly, so closing the issue as there where no other reports regarding GUI apps freezing.
