### ISSUE TITLE
Upgrading to new version

### ISSUE THREAD

**Issue by davorg** [VSWSL/Fedora-WSL#28]
I installed this from the Microsoft Store about a year ago. That gave me Fedora 38 - which I've been very happy with.

But the release of Fedora 40, means Fedora 38 will be unsupported by the Fedora project from the middle of next month (May 2024). So it's time to upgrade.

I've installed an upgrade from the Microsoft Store, which says it's version 39. How do I get that version to run under WSL? And when will Fedora 40 be available through this project?

**Comment by vineelsai26** [comment]
Updates from the Microsoft store after WSL has been installed don't do anything unless you are resetting your WSL, which will wipe all the data inside WSL. Once installed any WSL should be treated like any regular Linux distro and you should keep it updated from the distro's repository.

which means in case of Fedora WSL you would update to Fedora 39/40 by following Fedora's upgrade guide for that specific release - https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-offline/

**Comment by davorg** [comment]
I've tried that and it doesn't seem to work. I get an error when I run `sudo dnf system-upgrade reboot`

> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down

**Comment by vineelsai26** [comment]
oh, seems like that's the page for upgrading for desktop install, try this https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-online/

**Comment by davorg** [comment]
Thanks. That has got me to Fedora 39. I'll try upgrading to Fedora 40 once it's been released for a few more weeks.
